language: objective-c

branches:
 only:
 - master

xcode_project: Gitster.xcodeproj
xcode_scheme: GitsterTests
osx_image: xcode7.2.1
xcode_sdk: iphonesimulator9.2 
before_install: gem install cocoapods

script:
- xcodebuild clean build test -project Swifternalization.xcodeproj -scheme SwifternalizationTests