language: objective-c

branches:
 only:
 - master

before_install:
  - gem install cocoapods

xcode_project: Gitster.xcodeproj
xcode_scheme: GitsterTests
osx_image: xcode7.2.1
xcode_sdk: iphonesimulator9.2 

script:
- xcodebuild clean build test -project Gitster.xcodeproj -scheme GitsterTests