language: objective-c

branches:
 only:
 - master

before_install:
  - rvm install 2.2.2
  - rvm use 2.2.2
  - gem install cocoapods

script:
- xcodebuild clean build test -workspace Gitster.xcworkspace -scheme Gitster -sdk iphonesimulator ONLY_ACTIVE_ARCH=N